### ISSUE TITLE
Pre 3.10 compatible?

### ISSUE THREAD

**Issue by nromashchenko** [Tharos-ux/gfatypes#4]
Hi,

I am interested in trying out your tool. I wonder if there is anything in the code that is not compatible with earlier python versions than 3.10, and if not, whether you could update the package in the index. I could get my hands dirty and just use/adapt the sources, but I'd like to just install a compatible version from pypi.

thanks

**Comment by dubssieg** [comment]
Hi, thanks for your interest and inquiry.
This package takes usage of the structural pattern matching which was introduced in 3.10.
As such, the code requires to be in 3.10 at least: however, it should be easy to set this up in a conda environnment.
Moving forward, support will be maintained for 3.10, but I highly encourage to run the latest version (3.12) of python, as the updates brings a lot of improvments towards used structures.
